#!/usr/bin/env sh

# Dumb ubuntu script for installing needed packages with apt. It's very aggressive.

if [[ $EUID -ne 0 ]]; then
    echo "ERROR: Install script must be run as sudo to install dependencies."
    exit 1
fi

apt install feh i3blocks ffmpeg scrot dunst xcompmgr shutter slop glances

# Install kitty terminal emulator
curl -L https://sw.kovidgoyal.net/kitty/installer.sh | sh /dev/stdin

pip install s-tui
